version: '3.8'

services:
  tg_bot:
    build:
      context: .
    environment:
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASS=mysecretpassword
      - DB_NAME=mydatabase
      - PGPASSWORD=mysecretpassword  
    volumes:
      - .:/app
    command: >
      sh -c "
      psql -h $DB_HOST -U $DB_USER -d $DB_NAME -f /app/migrations/migration.sql &&
      python main.py
      "
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: mydatabase
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data: