version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      OPENAI_API_KEY: "your_openai_api_key"  # Замените на ваш ключ OpenAI
    volumes:
      - .:/app

